server:
  port: 8082

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:mysql://localhost:3306/ead_course
    username: user-course
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

ead:
  api:
    url:
      auth-user: 'http://ead-authuser-service'
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost